name: First Workflow

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.1
     - name: Setup Java JDK
       uses: actions/setup-java@v5.1.0
       with:
        java-version: 17
        
